#!/bin/bash
# Initialize Complex Task Workspace
# Usage: ./init-task.sh <task-name>
#
# NOTE: This script creates an empty workspace for manual requirement drafting.
#       For direct automation, call the skill directly:
#         /universal-complex-task "your requirement description"
#       The skill will auto-populate all files; you only need to confirm at 3 checkpoints.

TASK_NAME="${1:-task-$(date +%s)}"
TASK_DIR=".agent/tasks/$TASK_NAME"

# Existence check: refuse to overwrite existing task
if [ -d "$TASK_DIR" ]; then
    echo "⚠️  Task '$TASK_NAME' already exists."
    if [ -f "$TASK_DIR/state.json" ]; then
        STATUS=$(grep '"status"' "$TASK_DIR/state.json" | head -1 | sed 's/.*: "\([^"]*\)".*/\1/')
        PHASE=$(grep '"phase"' "$TASK_DIR/state.json" | head -1 | sed 's/.*: "\([^"]*\)".*/\1/')
        echo "   Status: $STATUS"
        echo "   Phase: $PHASE"
    fi
    echo ""
    echo "To resume: /universal-complex-task --resume $TASK_NAME"
    echo "To force new (archives old): /universal-complex-task --force $TASK_NAME"
    echo "To inspect: /universal-complex-task --inspect $TASK_NAME"
    exit 1
fi

mkdir -p "$TASK_DIR/milestones"
mkdir -p "$TASK_DIR/snapshots"
mkdir -p ".agent/templates/decomposition"
mkdir -p ".agent/templates/contracts"

# Generate state.json
cat > "$TASK_DIR/state.json" << EOF
{
  "task_id": "$TASK_NAME",
  "status": "INIT",
  "phase": "U_PARSED",
  "current_milestone": null,
  "current_feature": null,
  "current_iteration": 0,
  "fix_depth": 0,
  "global_iteration": 0,
  "planning_adjustments": 0,
  "completed_milestones": [],
  "completed_features": [],
  "pending_features": [],
  "frozen_files": [],
  "last_role": "O",
  "last_action": "INIT",
  "last_result": "OK",
  "last_timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "budget": {
    "files_modified": 0,
    "files_max": 100,
    "tool_calls": 0,
    "tool_calls_max": 200
  }
}
EOF

cat > "$TASK_DIR/01-user-intent.md" << 'EOF'
# 01 User Intent (U)

## Raw Input
{Will be auto-populated by O if skill is called directly}

## Explicit Requirements
- {to be extracted by O}

## Implicit Requirements
- {to be inferred by O}

## Anti-Requirements
- {to be defined by O}
EOF

cat > "$TASK_DIR/02-structured-spec.md" << 'EOF'
# 02 Structured Spec (S) — Human Confirm Layer 1

### Scope Summary
{to be generated by O}

### Human Confirmation
- [ ] Pending confirmation
EOF

cat > "$TASK_DIR/03-validation-contract.md" << 'EOF'
# 03 Validation Contract (C) — Human Spot-Check Layer 2

### Contract Metadata
- Frozen: false

### Assertions
{to be generated by O}

### Human Spot-Check
- [ ] Pending spot-check
EOF

cat > "$TASK_DIR/04-features-and-milestones.md" << 'EOF'
# 04 Features & Milestones

### Features
{to be planned by O}

### Milestones
{to be staged by O}

### Human Confirmation
- [ ] Pending approval
EOF

cat > "$TASK_DIR/05-audit-log.md" << 'EOF'
# Audit Log (A) — Append Only

| Timestamp | Role | Action | Target | Input | Output | Decision | Human |
|-----------|------|--------|--------|-------|--------|----------|-------|
EOF

cat > "$TASK_DIR/06-memory.md" << 'EOF'
# Memory (M) — Cross-Task Experience

## This Task
{to be accumulated}

## Cross-Task Merge Status
- [ ] Pending merge to .agent/memory.md
EOF

touch "$TASK_DIR/milestones/.gitkeep"

echo "✅ Task workspace initialized: $TASK_DIR"
echo ""
echo "Usage A (Recommended): Direct skill call"
echo "  /universal-complex-task "your requirement description""
echo "  → O auto-populates all files; you confirm at 3 checkpoints."
echo ""
echo "Usage B (Manual): Edit 01-user-intent.md, then call skill."
echo ""
echo "State file created: $TASK_DIR/state.json"
echo "This file is the single source of truth for execution state."
